### ISSUE TITLE
IE8

### ISSUE THREAD

**Issue by BilalWachah** [FaroeMedia/selectator#12]
You plugin does not work in IE8, maybe even IE9.
Although it does open the a list as a dropdownbox it does NOT allow you to select a item in the list.
The list stays open and nothing happens.

**Comment by jogvana** [comment]
We will look into this and get back asap.

**Comment by ingipingi** [comment]
IE support should be working again now :+1:

**Comment by BilalWachah** [comment]
Awesome that was fast:) Thanks!
