### ISSUE TITLE
Text going out of box

### ISSUE THREAD

**Issue by blincivi** [FaroeMedia/selectator#14]
If a select option has a text, which is longer than the select box and then you activate selectator, the text will go out of the box.

Reproduce:
Win 7, Firefox 38.0.1 
http://opensource.faroemedia.com/selectator/

Replace with below select option,
click on activate selectator.

```
<select style="display: none;" id="select2" name="select2">
			<option value="1" class="option_one">One one one one One one one one One one one one One one one one</option>
			<option value="2" class="option_two">Two</option>
		</select>
```

-> Text goes out of box

**Comment by jogvana** [comment]
Thanks for the notice. We'll look at it asap and get back.

**Comment by ingipingi** [comment]
Should be fixed now
