### ISSUE TITLE
adding check box to drop down options

### ISSUE THREAD

**Issue by rppgoud** [FaroeMedia/selectator#16]
Dear Developer,
                         i want to add the check box to the options and make it effectevely working.can you please help me with this issue

**Comment by jogvana** [comment]
Hi. Thanks for your feedback. We'll get in touch with you asap next week.

**Comment by ingipingi** [comment]
I'm sorry but selectator doesn't have that functionality at this point.

But if you check out this page, you'll have several different plugins with that functionality:
http://www.jqueryrain.com/demo/jquery-multiselect-plugin/
