### ISSUE TITLE
Selecting value programmatically

### ISSUE THREAD

**Issue by PavSidhu** [FaroeMedia/selectator#19]
If I wanted to set the default value, how would I do so? Is there an option I could include during the initial configuration? Thanks.

**Comment by ingipingi** [comment]
Setting the default value of the source select element, will also set the default of selectator.
If your setting the default value of the source select element programmatically at runtime, you'll need to trigger a change event on the source select element. In jQuery this is done something like this:
```
$('#mySelectElement').trigger('change');
```

**Comment by PavSidhu** [comment]
Fantastic, thank you.
